name: Publish Docker image

#on:
#  release:
#    types: [published]

on: push
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.stg-platform.hc.ai
          username: ian2
          password: ${{ secrets.HARBOR_USER_PASSWORD }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          repository: ian2/fromgithub
          push: true
          tags: ian2/fromgithub:latest


